### ISSUE TITLE
Variables does not show / Ruby on Rails 5.0.5 (Puma)

### ISSUE THREAD

**Issue by ycrepeau** [ruby-debug/ruby-debug-ide#122]
Fast Debugger (ruby-debug-ide 0.6.1.beta7, debase 0.2.2.beta10, file filtering is supported) listens on 127.0.0.1:1234
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0.8.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
=> Booting Puma
=> Rails 5.0.5 application starting in development on http://localhost:3000

Note: Using ruby 2.3.1 using RVM

IDE: VS Code launched from Terminal.app running on Mac OS X

Issue: I figured out how to launch the server in debug mode and everything works as expected as long as I don't set a breakpoint.

If I set a breakpoint, the execution stops BUT no variables are displayed. If I don't resume the server, the thread is killed and restarted (after about 30 or 40 seconds).

**Comment by ViugiNick** [comment]
@ycrepeau Looks like it's a VS Code plugin issue, can you please turn on the `verbose` key and attach the verbose output, so I can find out what is the problem with protocol

**Comment by valich** [comment]
Incomplete.
