### ISSUE TITLE
Rubymine not run debug mode

### ISSUE THREAD

**Issue by mayribeiro** [ruby-debug/ruby-debug-ide#162]
> /home/vagrant/.rbenv/versions/1.8.7-p374/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /home/vagrant/.rbenv/versions/1.8.7-p374/lib/ruby/gems/1.8/gems/ruby-debug-ide-0.7.0.beta6/lib/ruby-debug-ide/xml_printer.rb:462: syntax error, unexpected '\n' (SyntaxError)

Can someone help me?

**Comment by ViugiNick** [comment]
@mayribeiro The last ruby-debug-ide version(https://rubygems.org/gems/ruby-debug-ide/versions/0.7.0.beta7) should help

**Comment by mayribeiro** [comment]
Thanks @ViugiNick
