### ISSUE TITLE
Error installing gem with ruby 2.6.2 - invalid option: -no-rdoc

### ISSUE THREAD

**Issue by adnanpirota** [ruby-debug/ruby-debug-ide#170]
It looks like ruby 2.6.2 does not support option: -no-rdoc and RubyMine fails to install the gemwith error: ... While executing gem ...(Option Parser::InvalidOption) invalid option: -no-rdoc. The option passed should be -no-documentation.

**Comment by adnanpirota** [comment]
Fixed if you install the latest version not the deafult one

**Comment by Benderg13** [comment]
ruby 2.6.5 also does not support option: -no-rdoc and RubyMine fails to install the gem with error: ... While executing gem ...(Option Parser::InvalidOption) invalid option: -no-rdoc. Could someone fix this issue or post how to fix the issue?

**Comment by ViugiNick** [comment]
@Benderg13 Could you try one of the latest RubyMine versions?

**Comment by Benderg13** [comment]
That worked, thank you!
