### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by coding-bunny** [ruby-debug/ruby-debug-ide#178]
Rubymine installed `ruby-debug-ide` version `0.8.0.beta6` (I still don't get why this IDE forces to use beta gems) and trying tod ebug anything results in segmentation faults.

Can't post the entire stack cause it exceeds the 65k chars

**Comment by ViugiNick** [comment]
@coding-bunny Could you please vote for the ticket here https://youtrack.jetbrains.com/issue/RUBY-24861

**Comment by ViugiNick** [comment]
@coding-bunny Did you have time to try custom gem (0.8.0.beta8)?
