### ISSUE TITLE
0.8.0.beta24 crash on Catalina

### ISSUE THREAD

**Issue by gisborne** [ruby-debug/ruby-debug-ide#193]
[ruby_2020-05-31-151940_Hermes.txt](https://github.com/ruby-debug/ruby-debug-ide/files/4708601/ruby_2020-05-31-151940_Hermes.txt)

**Comment by gisborne** [comment]
Same result with Ruby 2.7.1

**Comment by jabamaus** [comment]
Hi Guyren,

What am I missing? Ruby-debug-ide doesn’t seem to have a branch with a
0.8.0 beta on it. Or does it?

James

**Comment by oleg-andreyev** [comment]
Looks like ruby-debug-ide is now supported by JetBrains, no? it seems that `ruby-debug-ide-0.8.0.beta24` is bundled with RubyMine

**Comment by brodock** [comment]
I'm asking the same question here: https://github.com/ruby-debug/ruby-debug-ide/issues/201 it seems there is a private fork.

**Comment by hurricup** [comment]
Issues about ruby-debug-ide 0.8.x (now it's 2.3.x+) should be submitted to the RubyMine tracker: https://youtrack.jetbrains.com/issues/RUBY
