### ISSUE TITLE
Release process and access to the source-code

### ISSUE THREAD

**Issue by brodock** [ruby-debug/ruby-debug-ide#201]
I'm a RubyMine user and long-time paying customer (the company I work for also pays a bunch of IDE licenses). It seems that as part of each RubyMine releases, `ruby-debug-ide` has improvements shipped and side-loaded, but never really publicly released.

By looking at https://rubygems.org/gems/ruby-debug-ide/versions the version numbers doesn't match by watch RubyMine installs:

```
ruby-debug-ide (2.3.0, 0.8.0.beta24)
    Author: Markus Barchfeld, Martin Krauskopf, Mark Moseley, JetBrains
    RubyMine Team
    Homepage: https://github.com/JetBrains/ruby-debug-ide
    License: MIT
    Installed at (2.3.0): /Users/brodock/.rvm/gems/ruby-2.6.6
                 (0.8.0.beta24): /Users/brodock/.rvm/gems/ruby-2.6.6

    IDE interface for ruby-debug.
```

Also it seems that you are handling a private fork at `https://github.com/JetBrains/ruby-debug-ide`, can you please clarify whats going on here?

**Comment by hurricup** [comment]
I'm not sure I understand your question. This is open-source debugger where everyone can contribute.

**Comment by brodock** [comment]
my question is why Jetbrains forked the own gem they have access to in this repository and are releasing a "private" version of that using the same name. This is confusing. They should either go back and publish the code here, in rubygems etc or change the name of their private fork for something like `jetbrains-ruby-debug-ide`when installed on our machines by the IDE.

**Comment by hurricup** [comment]
Because we decided to make a separate close-sourced version of the gem, obviously. 
Still thinking what to do with naming.

**Comment by hurricup** [comment]
And I believe originally this is not JetBrains gem. JetBrains employees just actively contributed into it. JetBrains projects are in https://github.com/JetBrains/

**Comment by brodock** [comment]
that's my point, if going closed source please use a different name and be public about it.
