### ISSUE TITLE
Incompatible with Ruby 3?

### ISSUE THREAD

**Issue by sedubois** [ruby-debug/ruby-debug-ide#209]
I just upgraded my system to Ruby 3.0.0 (`ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]` installed with Homebrew), then tried starting my Rails server in IntelliJ IDEA in debug mode, which gave the popup question "The debugging gems are not installed. Would you like to install them?". I answered yes but then got the error. Same problem when I try again.

<img width="1382" alt="Screenshot 2020-12-29 at 09 51 14" src="https://user-images.githubusercontent.com/4217871/103272066-2a763000-49bc-11eb-9d01-cbd93f769ee3.png">

**Comment by hurricup** [comment]
You are installing jetbrains version of the debugger. Please, report the bug https://youtrack.jetbrains.com/issues/RUBY

**Comment by sedubois** [comment]
OK, created this ticket: https://youtrack.jetbrains.com/issue/RUBY-27575

**Comment by lifesboy** [comment]
Just update Rubymine to 2021.1.2 work for me
