### ISSUE TITLE
Whether to support debugging hotswap(hot code replace)?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [ruby-debug/ruby-debug-ide#211]
Whether to support debugging hotswap(hot code replace)?

it is very useful for debugging

**Comment by hurricup** [comment]
How do you see it considering monkey patching and stuff?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
Are there any supported debugger programs?I am a novice

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> 考虑到猴子修补和东西，您如何看待它？

Are there any supported debugger programs?I am a novice

**Comment by hurricup** [comment]
> Are there any supported debugger programs?I am a novice

Not sure I understand your question.
