### ISSUE TITLE
Uncaught exception: superclass mismatch for class SyntaxError

### ISSUE THREAD

**Issue by vikash-saxena** [ruby-debug/ruby-debug-ide#46]
Fast Debugger (ruby-debug-ide 0.4.23.beta1, debase 0.0.9) listens on 127.0.0.1:62941
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0.8.1)
      debugger-ruby_core_source (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/i386-mingw32/psych.so: warning: already initialized constant Psych::Parser::ANY
c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/i386-mingw32/psych.so: warning: already initialized constant Psych::Parser::UTF8
c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/i386-mingw32/psych.so: warning: already initialized constant Psych::Parser::UTF16LE
c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/i386-mingw32/psych.so: warning: already initialized constant Psych::Parser::UTF16BE
Uncaught exception: superclass mismatch for class SyntaxError
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych/syntax_error.rb:5:in `<module:Psych>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych/syntax_error.rb:1:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych.rb:1:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych.rb:1:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_hash.rb:2:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_hash.rb:2:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_options.rb:1:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_options.rb:1:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/configuration.rb:2:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/configuration.rb:2:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/railtie.rb:2:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/railtie.rb:2:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/engine.rb:1:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/engine.rb:1:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/plugin.rb:1:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/plugin.rb:1:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/application.rb:3:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/application.rb:3:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails.rb:10:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails.rb:10:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/all.rb:1:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/all.rb:1:in`<top (required)>'
    C:/Vikash/aptana_workspace/RailsDemoApp1/config/application.rb:3:in `require'
    C:/Vikash/aptana_workspace/RailsDemoApp1/config/application.rb:3:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/commands.rb:53:in `require'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/commands.rb:53:in`block in <top (required)>'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/commands.rb:50:in `tap'
    c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/railties-3.2.16/lib/rails/commands.rb:50:in`<top (required)>'
    C:/Vikash/aptana_workspace/RailsDemoApp1/script/rails:6:in `require'
    C:/Vikash/aptana_workspace/RailsDemoApp1/script/rails:6:in`<top (required)>'
    c:/RailsInstaller/Ruby2.0.0/bin/rdebug-ide:23:in `load'
    c:/RailsInstaller/Ruby2.0.0/bin/rdebug-ide:23:in`<main>'
c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych/syntax_error.rb:5:in `<module:Psych>': superclass mismatch for class SyntaxError (TypeError)
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych/syntax_error.rb:1:in`<top (required)>'
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych.rb:1:in `require'
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/psych.rb:1:in`<top (required)>'
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_hash.rb:2:in `require'
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_hash.rb:2:in`<top (required)>'
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_options.rb:1:in `require'
    from c:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/activesupport-3.2.16/lib/active_support/ordered_options.rb:1:in`<top (required)>'

**Comment by mystdeim** [comment]
I have the save error!

**Comment by os97673** [comment]
> I have the save error!

could you please provide a test to reproduce the problem
