### ISSUE TITLE
cannot load such file -- debase in IntelliJ IDEA 14.1.3

### ISSUE THREAD

**Issue by buzzware** [ruby-debug/ruby-debug-ide#71]
/Users/gary/.rvm/rubies/ruby-2.1.5/bin/ruby -e at_exit{sleep(1)};$stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/gary/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/bin/rdebug-ide --disable-int-handler --evaluation-timeout 10 --rubymine-protocol-extensions --port 59728 --dispatcher-port 59729 -- /Users/gary/.rvm/gems/ruby-2.1.5/bin/rspec /Users/gary/repos/freewheeler/mobile/free_intel/spec/record_store_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter --example "FreeIntel::RecordStore should insert and get"
Testing started at 1:46 PM ...
/Users/gary/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide.rb:8:in `require': cannot load such file -- debase (LoadError)
	from /Users/gary/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/lib/ruby-debug-ide.rb:8:in `<top (required)>'
	from /Users/gary/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/bin/rdebug-ide:8:in `require_relative'
	from /Users/gary/.rvm/gems/ruby-2.1.5/gems/ruby-debug-ide-0.4.32/bin/rdebug-ide:8:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1

**Comment by os97673** [comment]
Please check if debase gem is installed.  If it is I'd try to re-install gems and the ruby sdk (sometime the problem is binary incompatibility caused by different versions of compiler/linker used to build sdk and gems

**Comment by os97673** [comment]
I believe the problem has been fixed, feel free to reopen if it is not.

**Comment by jbedworth** [comment]
I'm hitting this today on Ruby 2.3, Rails 5.0.0.beta 3, ruby-debug-ide 0.0.0 and debase 0.2.1 freshly reinstalled.

**Comment by os97673** [comment]
and what is the message you see?

**Comment by jbedworth** [comment]
john$ rails c
/Users/john/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:8:in `require': cannot load such file -- debase (LoadError)

bundle show debase says "no gem by that name"; however, running gem server shows:

debase 0.2.1 [rdoc] [www] - depends on debase-ruby_core_source, rake, test-unit.
debase is a fast implementation of the standard Ruby debugger debug.rb for Ruby 2.0 

debase 0.2.2.beta7 [rdoc] [www] - depends on debase-ruby_core_source, rake, test-unit.
debase is a fast implementation of the standard Ruby debugger debug.rb for Ruby 2.0 

debase-ruby_core_source 0.8.6 [rdoc] [www] - depends on archive-tar-minitar, rake.
Provide Ruby core source files 

debug_inspector 0.0.2 [rdoc] [www]
A Ruby wrapper for the MRI 2.0 debug_inspector API 

No clue where the beta version is coming from.  I just did gem install debase.

**Comment by jbedworth** [comment]
strangely, debugging seems to be working fine in rubymine.  I just can not do "rails -c"

**Comment by os97673** [comment]
Well, it is expected.  Rubymine adds special "spells" to make it works without adding ruby-debug-ide and debase to Gemfile. If you want to use them from `rails -c` you need to add them to your Gemfile (though I'm not sure why you may want to have this functionality)

**Comment by jbedworth** [comment]
rails -c is pretty important functionality.  I don't think it's acceptable that the rails console crashes on startup just because you want to debug your app in rubymine occasionally.

**Comment by os97673** [comment]
Hmm, do you have ruby-debug-ide in your Gemfile?

**Comment by jbedworth** [comment]
yes, i added it to the development group

**Comment by os97673** [comment]
why do you need it in the Gemfile.  Rubymine will work w/o having ruby-debug-ide there.

**Comment by jbedworth** [comment]
Yes, you're absolutely right.  I can work-around this bug by taking it out of my gemfile for the project.  Still, I wonder why this is happening.

**Comment by os97673** [comment]
The problem with specifying dependencies for the gem is that it requires ruby-debug-base for mri 1.8 and jruby, ruby-debug-base19 for mri 1.9 and debase for ruby 2.x.  I've tried to specify this in gemspec but failed :(  So if you know how to do this - you are welcome ;)

**Comment by ihave58** [comment]
I am still facing the issues here. The debugger starts from RubyMine and remote rdebug-ide crashes  immediately. Here is the log, Kindly help resolving this:

[ec2-user@ip-10-147-40-29 ~]$ rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- $COMMAND$
Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 0.0.0.0:1234
Uncaught exception: cannot load such file -- /home/ec2-user/$
	/usr/bin/rdebug-ide:23:in `load'
	/usr/bin/rdebug-ide:23:in `<main>'
/usr/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_load': cannot load such file -- /home/ec2-user/$ (LoadError)
	from /usr/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_program'
	from /usr/lib/ruby/gems/2.1.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:130:in `<top (required)>'
	from /usr/bin/rdebug-ide:23:in `load'
	from /usr/bin/rdebug-ide:23:in `<main>'
