### ISSUE TITLE
Gem breaks everywhere when no breakpoints set

### ISSUE THREAD

**Issue by NekoNova** [ruby-debug/ruby-debug-ide#77]
This started with the latest update of Rubymine.
But this gem causes my app to break on every single line now.
Even when no breakpoints are set.

**Comment by denofevil** [comment]
This problem is caused by debase gem, you can downgrade it to 0.2.2.beta6 as a workaround. Please watch [this issue](https://youtrack.jetbrains.com/issue/RUBY-17990) for updates

**Comment by NekoNova** [comment]
thanks for the fast response! 
will give it a spin and keep tracking the issue.
