### ISSUE TITLE
Hangs Starting Thin

### ISSUE THREAD

**Issue by yagni** [ruby-debug/ruby-debug-ide#78]
I'm running ruby-debug-ide with the following syntax:

`rdebug-ide --port 1234 --dispatcher-port 26162 --host 0.0.0.0 -- /usr/local/bundle/bin/thin --ssl --ssl-cert-file $SSL_CERT_FILE --ssl-key-file $SSL_KEY_FILE --prefix /api/reagents -p 443 start`

The odd thing is I get the message that Fast Debugger is listening on 0.0.0.0:1234 but thin never starts. However, if I Ctrl^C, some process ends (I'm assuming rdebug-ide) and thin then starts up. Any ideas what could be going on here?

**Comment by denofevil** [comment]
Yes. When you start application through the rdebug-ide, it is stopped at the very first line and execution does not continue until you attach an IDE to this process

**Comment by yagni** [comment]
Aha, that was it, thanks! Works great!
