### ISSUE TITLE
Failed to load ruby file in a path that contains Chinese characters

### ISSUE THREAD

**Issue by albertgrain** [ruby-debug/ruby-debug-ide#81]
I  wrote a simple ruby file with Eclipse Aptana plugin.
When I put the file in a folder that contains Chinese character in the name, ruby debug send error message as follows:
(BTW, if I move the file into a folder without Chinese characters, it will run ok. I am using ruby 2.3.1)

Thanks for your attention and waiting for a reply.

Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 127.0.0.1:4223
Uncaught exception: cannot load such file -- D:/360����/Kevin/Test/test.rb
	D:/Ruby23/bin/rdebug-ide:23:in `load'
	D:/Ruby23/bin/rdebug-ide:23:in `<main>'
D:/Ruby23/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_load': cannot load such file -- D:/360����/Kevin/Test/test.rb (LoadError)
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_program'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:130:in `<top (required)>'
	from D:/Ruby23/bin/rdebug-ide:23:in `load'
	from D:/Ruby23/bin/rdebug-ide:23:in `<main>'

**Comment by denofevil** [comment]
@albertgrain sorry for the delayed reply.
I'm not sure that this bug is ruby-debug-ide fault. I was not able to run (without debug) ruby program that is stored in folder with Chinese characters from the command line too
